naam = str(input("voer je naam in "))
adres = str(input("voer je adres in "))
postcode = str(input("voer je postcode in "))
woonplaats = str(input("voer je woonplaats in "))

print("------------------------------")
print("|  Naam      : ", naam)
print("|  Adres     : ", adres)
print("|  Postcode  : ", postcode)
print("|  Woonplaats: ", woonplaats)
print("------------------------------")